# Data Analysis and Preprocessing on Airline Data

Day 3 Lab exercise:
 
Lab Exercise: Data Analysis and Preprocessing on Airline Data
Objective:
Analyze and preprocess an airline dataset with the following attributes:
Time-related Attributes: Year, Month, DayofMonth, DayOfWeek, CRSDepTime, CRSArrTime
Location-related Attributes: OriginAirportID, OriginAirportName, OriginCity, OriginState, DestAirportID, DestAirportName, DestCity, DestState
Flight Performance Metrics: DepDelay, DepDel15, ArrDelay, ArrDel15, Cancelled
Carrier Information: Carrier
Lab Tasks:
Data Loading and Exploration:
Load the dataset and display the first few rows.
Check for missing values and summarize the dataset.
Preprocessing:
Handling Missing Data:
Identify attributes with missing values and apply appropriate techniques to handle them.
Feature Encoding:
Convert categorical variables like Carrier, OriginState, and DestState into numeric format using one-hot encoding or label encoding.
Feature Scaling:
Normalize numeric features like DepDelay and ArrDelay using Min-Max Scaling.
Feature Transformation:
Create new features such as FlightDuration by calculating the time difference between CRSArrTime and CRSDepTime.
Exploratory Data Analysis (EDA):
Statistical Summary:
Provide a summary of delays (DepDelay, ArrDelay) using mean, median, and standard deviation.
Visualization:
Plot the distribution of DepDelay and ArrDelay.
Analyze cancellation trends by Carrier or DayOfWeek using bar plots.
Postprocessing:
Outlier Detection:
Identify outliers in DepDelay and ArrDelay using statistical techniques such as the IQR method.
Treat the outliers by capping or removing them.
Categorical Aggregation:
Group the data by OriginCity and calculate the average departure delay per city.
Analysis and Insights:
Identify the top 5 airports with the highest average departure delays.
Analyze whether cancellations are more likely to occur for certain carriers or days of the week.
Deliverables:
A clean, preprocessed dataset.
Plots and tables summarizing the analysis.
Key insights derived from the EDA.

In [1]:
# import python library
import pandas as pd
import numpy as np

# Load the dataset

In [2]:
df = pd.read_csv('flights.csv') 
df.head()

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,DL,15304,Tampa International,Tampa,FL,12478,John F. Kennedy International,New York,NY,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,WN,14122,Pittsburgh International,Pittsburgh,PA,13232,Chicago Midway International,Chicago,IL,710,3,0.0,740,22,1,0
2,2013,9,7,6,AS,14747,Seattle/Tacoma International,Seattle,WA,11278,Ronald Reagan Washington National,Washington,DC,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
4,2013,5,16,4,DL,13931,Norfolk International,Norfolk,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,545,-1,0.0,728,-9,0,0

# Summarize the dataset

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271940 entries, 0 to 271939
Data columns (total 20 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Year               271940 non-null  int64
 1   Month              271940 non-null  int64
 2   DayofMonth         271940 non-null  int64
 3   DayOfWeek          271940 non-null  int64
 4   Carrier            271940 non-null  object
 5   OriginAirportID    271940 non-null  int64
 6   OriginAirportName  271940 non-null  object
 7   OriginCity         271940 non-null  object
 8   OriginState        271940 non-null  object
 9   DestAirportID      271940 non-null  int64
 10  DestAirportName    271940 non-null  object
 11  DestCity           271940 non-null  object
 12  DestState          271940 non-null  object
 13  CRSDepTime         271940 non-null  int64
 14  DepDelay           271940 non-null  int64
 15  DepDel15           269179 non-null  float64
 16  CRSArrTime         271940 non-null  int64
 17  ArrDelay           271940 non-null  int64
 18  ArrDel15           271940 non-null  int64
 19  Cancelled          271940 non-null  int64
dtypes: float64(1), int64(12), object(7)
memory usage: 41.5+ MB

# Check for missing values

In [4]:
df.isnull().sum()

Year                    0
Month                   0
DayofMonth              0
DayOfWeek               0
Carrier                 0
OriginAirportID         0
OriginAirportName       0
OriginCity              0
OriginState             0
DestAirportID           0
DestAirportName         0
DestCity                0
DestState               0
CRSDepTime              0
DepDelay                0
DepDel15             2761
CRSArrTime              0
ArrDelay                0
ArrDel15                0
Cancelled               0
dtype: int64

# Preprocessing:

In [5]:
# Handling Missing Data:
# Identify attributes with missing values and apply appropriate techniques to handle them.
df['DepDel15'] = df['DepDel15'].fillna(df['DepDel15'].mean())

In [6]:
# Convert categorical variables like Carrier, OriginState, 
# and DestState into numeric format using one-hot encoding or label encoding.

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['Carrier'] = label_encoder.fit_transform(df['Carrier'])
df['OriginState'] = label_encoder.fit_transform(df['OriginState'])
df['DestState'] = label_encoder.fit_transform(df['DestState'])

In [7]:
from sklearn.preprocessing import MinMaxScaler

# Instantiate the MinMaxScaler
scaler = MinMaxScaler()

# Scale the specified columns
df[['Carrier', 'OriginState', 'DestState']] = scaler.fit_transform(df[['Carrier', 'OriginState', 'DestState']])

In [8]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,0.266667,15304,Tampa International,Tampa,0.171429,12478,John F. Kennedy International,New York,0.657143,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,0.933333,14122,Pittsburgh International,Pittsburgh,0.771429,13232,Chicago Midway International,Chicago,0.257143,710,3,0.0,740,22,1,0
2,2013,9,7,6,0.133333,14747,Seattle/Tacoma International,Seattle,0.971429,11278,Ronald Reagan Washington National,Washington,0.142857,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,0.666667,13930,Chicago O'Hare International,Chicago,0.257143,11042,Cleveland-Hopkins International,Cleveland,0.685714,804,35,1.0,1027,33,1,0
4,2013,5,16,4,0.266667,13931,Norfolk International,Norfolk,0.942857,10397,Hartsfield-Jackson Atlanta International,Atlanta,0.200000,545,-1,0.0,728,-9,0,0

In [9]:
# Create new features such as FlightDuration by calculating the time difference between CRSArrTime and CRSDepTime.

df['CRSArrTime'] = pd.to_datetime(df['CRSArrTime'], format='%H%M', errors='coerce')
df['CRSDepTime'] = pd.to_datetime(df['CRSDepTime'], format='%H%M', errors='coerce')

df['FlightDuration'] = (df['CRSArrTime'] - df['CRSDepTime']).dt.total_seconds() / 60

In [10]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,...,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled,FlightDuration
0,2013,9,16,1,0.266667,15304,Tampa International,Tampa,0.171429,12478,...,New York,0.657143,1900-01-01 15:39:00,4,0.0,1900-01-01 18:24:00,13,0,0,165.0
1,2013,9,23,1,0.933333,14122,Pittsburgh International,Pittsburgh,0.771429,13232,...,Chicago,0.257143,1900-01-01 07:10:00,3,0.0,1900-01-01 07:40:00,22,1,0,30.0
2,2013,9,7,6,0.133333,14747,Seattle/Tacoma International,Seattle,0.971429,11278,...,Washington,0.142857,1900-01-01 08:10:00,-3,0.0,1900-01-01 16:14:00,-7,0,0,484.0
3,2013,7,22,1,0.666667,13930,Chicago O'Hare International,Chicago,0.257143,11042,...,Cleveland,0.685714,1900-01-01 08:04:00,35,1.0,1900-01-01 10:27:00,33,1,0,143.0
4,2013,5,16,4,0.266667,13931,Norfolk International,Norfolk,0.942857,10397,...,Atlanta,0.200000,1900-01-01 05:45:00,-1,0.0,1900-01-01 07:28:00,-9,0,0,103.0

# Exploratory Data Analysis (EDA):
### Statistical Summary:

In [11]:
# Provide a summary of delays (DepDelay, ArrDelay) using mean, median, and standard deviation.
df[['DepDelay', 'ArrDelay']].describe()

            DepDelay       ArrDelay
count  271940.000000  271940.000000
mean       10.350449       6.496650
std        35.673710      38.230331
min       -63.000000     -75.000000
25%        -4.000000     -11.000000
50%        -1.000000      -3.000000
75%         9.000000      10.000000
max      1425.000000    1440.000000

# Visualization:

In [ ]:
# Plot the distribution of DepDelay and ArrDelay.
# Analyze cancellation trends by Carrier or DayOfWeek using bar plots.

import matplotlib.pyplot as plt
import seaborn as sns

# Plot distribution of delays
plt.figure(figsize=(12, 6))
sns.histplot(df['DepDelay'], kde=True, color='blue', label='DepDelay')
sns.histplot(df['ArrDelay'], kde=True, color='orange', label='ArrDelay')
plt.legend()
plt.title("Distribution of Departure and Arrival Delays")
plt.show()

# Cancellation trends by Carrier
plt.figure(figsize=(12, 6))
sns.countplot(x='Carrier', hue='Cancelled', data=df)
plt.title("Cancellations by Carrier", fontsize=16)
plt.xlabel("Carrier", fontsize=12)
plt.ylabel("Count", fontsize=12)

# Rotate x-axis labels
plt.xticks(rotation=45, fontsize=10)

# Show the plot
plt.tight_layout()
plt.show()

# Outlier Detection:

In [ ]:
sns.boxplot(df['DepDelay'])

In [ ]:
# Identify outliers in DepDelay and ArrDelay using statistical techniques such as the IQR method.
# Treat the outliers by capping or removing them.

Q1 = df['DepDelay'].quantile(0.25)
Q3 = df['DepDelay'].quantile(0.75)
IQR = Q3 - Q1

# Cap outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df['DepDelay'] = np.clip(df['DepDelay'], lower_bound, upper_bound)

In [ ]:
sns.boxplot(df['DepDelay'])

In [ ]:
sns.boxplot(df['ArrDelay'])

In [ ]:
# remove outlier in ArrDelay column
Q1 = df['ArrDelay'].quantile(0.25)
Q3 = df['ArrDelay'].quantile(0.75)
IQR = Q3 - Q1

# Cap outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df['ArrDelay'] = np.clip(df['ArrDelay'], lower_bound, upper_bound)

In [ ]:
# check outlier is remove or not
sns.boxplot(df['ArrDelay'])

In [ ]:
# Categorical Aggregation:
# Group the data by OriginCity and calculate the average departure delay per city.

avg_dep_delay_per_city = df.groupby('OriginCity')['DepDelay'].mean().sort_values(ascending=False)
avg_dep_delay_per_city

# Analysis and Insights:

In [ ]:
# Identify the top 5 airports with the highest average departure delays.

top_5_airports = avg_dep_delay_per_city.head(5)
top_5_airports

In [ ]:
# Analyze whether cancellations are more likely to occur for certain carriers or days of the week.
cancellations_by_day = df.groupby('DayOfWeek')['Cancelled'].mean()
cancellations_by_day

# Deliverables:

In [ ]:
df.to_csv('cleaned_airline_data.csv', index=False)